name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *" # Обновляется каждые 6 часов
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: afrideva/gh-snake-action@v1.0.1
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate new snake animation" || exit 0
          git push
